model_list:
  - model_name: openai/gpt-4o
    litellm_params:
      model: openai/gpt-4o

  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini

  - model_name: openai/o3-mini
    litellm_params:
      model: openai/o3-mini

  - model_name: gemini/gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash

  - model_name: gemini/gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro

  - model_name: bedrock/anthropic.claude-3-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-sonnet

  - model_name: bedrock/anthropic.claude-35-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-35-sonnet

  - model_name: bedrock/anthropic.claude-37-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-37-sonnet

  - model_name: claude-3-7-sonnet-latest
    litellm_params:
      model: bedrock/anthropic.claude-37-sonnet

  - model_name: DeepSeek-R1
    litellm_params:
      model: deepseek/DeepSeek-R1

litellm_settings:
  drop_params: true
  callbacks: custom_callbacks.proxy_handler_instance
